CREATE TABLE IF NOT EXISTS guestbook (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  message VARCHAR(256) NOT NULL,
  time_stamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_timestamp (time_stamp DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;